"""Add trainer_id column to users

Revision ID: 5261ee3db5c7
Revises: 59c876289e17
Create Date: 2025-07-08 21:20:46.837231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5261ee3db5c7'
down_revision = '59c876289e17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('trainer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['trainer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey') # type: ignore
    op.drop_column('users', 'trainer_id')
    # ### end Alembic commands ###
